version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: linuxserver_code-server
    environment:
      - PUID=501
      - PGID=501
      - TZ=Asia/Seoul
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped