version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${DIST}:/dist
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${PORT}:80
