version: '3'
services:
  jupyter:
    container_name: jupyterlab
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - jupyter_data:/home/jovyan/.local/share/jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  jupyter_data: