version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${PORT}:27017
    volumes:
      - ./db:/data/db
